export const Images = {
	loginBackground: require("../assets/background/styler_bg.png"),
	logo: require("../assets/logo/logo.png"),
	back: require("../assets/back/back.png"),
	salonIcon: require("../assets/salon_icon/salon_icon.png"),
	freelancerIcon: require("../assets/freelancer_icon/freelancer_icon.png"),
	novoIconLogo: require("../assets/n_icon/styler_logo_icon.png"),
	visibilityHideIconLogin: require("../assets/hide-button/hide_button.png"),
	visibilityIconLogin: require("../assets/visibility-button/visibility-button.png"),
	forgotPassword: require("../assets/forgot_blue/forgot_blue.png"),
	topCornerRegister: require("../assets/top_corner_bg/top_corner_bg.png"),
	downArrow: require("../assets/down_arrow/down-arrow.png"),
	downFilledArrow: require("../assets/phone-drop/drop-down.png"),
	check: require("../assets/check/blue_check_selected.png"),
	unCheck: require("../assets/unCheck/blue_check.png"),
	submitBlue: require("../assets/submit_blue/submit_blue.png"),
	crossIcon: require("../assets/cross/cross.png"),
	searchIcon: require("../assets/ic_search/ic_search.png"),
	settingsIcon: require("../assets/ic_settings/ic_settings.png"),
	avatar: require("../assets/ic_avatar/ic_avatar.png"),
	arrowRight: require("../assets/arrow_right/next_arrow.png"),
	postsIconGrey: require("../assets/posts_grey/posts_grey.png"),
	postsIconBlue: require("../assets/posts_blue/posts_blue.png"),
	likeGrey: require("../assets/like_grey/like_grey.png"),
	likeBlue: require("../assets/like_blue/like_blue.png"),
	favoriteGrey: require("../assets/fav_grey/fav_grey.png"),
	favoriteBlue: require("../assets/fav_blue/fav_blue.png"),
	playButton: require("../assets/ic_play/ic_play-button.png"),
	greenRoundPlusIcon: require("../assets/floating/floating.png"),
	noDataFound: require("../assets/no_data_found/green_empty.png"),
	delete: require("../assets/delete/delete.png"),
	addBlue: require("../assets/add_blue/add_blue.png"),
	addBlack: require("../assets/add_black/add_black.png"),
	adddedBlueTick: require("../assets/added_blue/added_blue.png"),
	salonSelected: require("../assets/salon_selected/salon_selected.png"),
	freelancerSelected: require("../assets/freelancer_selected/freelancer_selected.png"),
	available: require("../assets/available/available.png"),
	notAvailable: require("../assets/not_available/not_available.png"),
	crossB: require("../assets/ic_cross_b/ic_cross_b.png"),
	noovooLogo: require("../assets/noovvoo_logo/noovvoo_logo.png"),
	notification: require("../assets/notification/notification.png"),
	mapsPinGrey: require("../assets/maps_pin_grey/maps_pin_grey.png"),
    starYellow: require("../assets/star_yellow/star_yellow.png"),
    phone:require("../assets/phone/phone.png"),
	message:require("../assets/message/message.png"),
	edit:require("../assets/edit/edit.png"),
	ic_avatar: require("../assets/ic_avatar/ic_avatar.png"),
	camera_white:require("../assets/camera_white/camera_white.png"),
	addressRect:require("../assets/address_rect/address_rect.png"),
	direction:require("../assets/ic_directions_blue/ic_directions_blue.png"),
	logo_big: require("../assets/logo_big/logo_big.png"),
	small_logo: require("../assets/small_logo/small_logo.png"),
};

export const TabImages = {
	unselected: [
		require("../assets/home/home.png"),
		require("../assets/ic_member/ic_member.png"),
		require("../assets/ic_booking/ic_booking.png"),
		require("../assets/ic_profile/ic_profile.png")
	],
	selected: [
		require("../assets/home_s/home_s.png"),
		require("../assets/ic_member_selected/ic_member_selected.png"),
		require("../assets/ic_booking_blue/ic_booking_blue.png"),
		require("../assets/profile/profile.png")
	]
};
